services:
  flask_gunicorn:
    container_name: flask_gunicorn
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "5000:5000"
  nginx:
    container_name: django_nginx
    build:
      context: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:5000"
    depends_on:
      - flask_gunicorn

volumes:
  static: